In [ ]:
import numpy as np

np.random.seed(0)

X = [[1, 2, 3, 4]]
X1 = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
class layer:
    def __init__(self, ninputs, nneurons):
        self.nneurons = nneurons
        self.weights = np.random.randn(ninputs, nneurons)
        self.biases = np.zeros((1, nneurons))
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases

In [ ]:
nNpL = [len(X[0]), 5, 4, 1]

layers = [layer(nNpL[i], nNpL[i+1]) for i in range(0, len(nNpL)-1)]

for i in range (0, len(layers)):
    if i == 0:
        print("inputs")
        print(X)
        layers[i].forward(X)
    else:
        layers[i].forward(layers[i-1].outputs)
    print("weights layer", i+1)
    print(layers[i].weights)
    if i != len(layers)-1:
        print("outputs layer", i+1)
    else:
        print("final outputs")
    print(layers[i].outputs)




inputs
[[1, 2, 3, 4]]
weights layer 1
[[-1.07075262  1.05445173 -0.40317695  1.22244507  0.20827498]
 [ 0.97663904  0.3563664   0.70657317  0.01050002  1.78587049]
 [ 0.12691209  0.40198936  1.8831507  -1.34775906 -1.270485  ]
 [ 0.96939671 -1.17312341  1.94362119 -0.41361898 -0.74745481]]
outputs layer 1
[[ 5.14084856 -1.71934101 14.43390622 -4.45430799 -3.02125828]]
weights layer 2
[[ 1.92294203  1.48051479  1.86755896  0.90604466]
 [-0.86122569  1.91006495 -0.26800337  0.8024564 ]
 [ 0.94725197 -0.15501009  0.61407937  0.92220667]
 [ 0.37642553 -1.09940079  0.29823817  1.3263859 ]
 [-0.69456786 -0.14963454 -0.43515355  1.84926373]]
outputs layer 2
[[25.4605941   7.43880251 18.91145761  5.09395216]]
weights layer 3
[[ 0.67229476]
 [ 0.40746184]
 [-0.76991607]
 [ 0.53924919]]
final outputs
[[8.33472643]]
